#!/usr/bin/env bash
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

TAG="${TAG:-v1.0.0}"
OUT="release_assets"

FILES=(queries.parquet cards.jsonl split_manifest.json leak_dropped_uids.json
       processed/train_query_instances.jsonl
       processed/valid_query_instances.jsonl
       processed/test_query_instances.jsonl
       processed/train_sequences.jsonl
       processed/item_map.parquet
       processed/item_card_review_pool_train_only.parquet
       processed/preprocess_config.json)

if [[ $# -gt 0 ]]; then DS_LIST=("$@"); else DS_LIST=(books); fi

mkdir -p "$OUT"

for ds in "${DS_LIST[@]}"; do
  src="data/preprocessed/$ds"
  [[ -d "$src" ]] || { echo "[abort] unknown dataset: $src" >&2; exit 1; }

  pack=("${FILES[@]}")
  missing=()
  for f in "${pack[@]}"; do [[ -f "$src/$f" ]] || missing+=("$f"); done
  if [[ ${#missing[@]} -gt 0 ]]; then
    echo "[abort] $ds is missing: ${missing[*]}" >&2; exit 1
  fi

  python3 - "$ds" <<'PY'
import json, sys
sys.path.insert(0, "src")
from config import canonical_eval_id, canonical_n, canonical_sha256, leak_json_path, processed_dir
ds = sys.argv[1]
dropped = {int(u) for u in json.load(open(leak_json_path(ds)))["combined_dropped_uids_union_both_splits"]}
kept = [o for o in map(json.loads, open(f"{processed_dir(ds)}/test_query_instances.jsonl", encoding="utf-8"))
        if int(o["uid"]) not in dropped]
n, sha, got = canonical_n(ds), canonical_sha256(ds), canonical_eval_id(kept)
if (n is not None and len(kept) != n) or (sha is not None and got != sha):
    raise SystemExit(f"[abort] {ds}: the processed/ being packaged differs from the reported "
                     f"evaluation set (count {len(kept):,} vs {n:,}, "
                     f"sha256 {got[:16]}… vs {(sha or '')[:16]}…)")
print(f"[check] {ds}: canonical {len(kept):,} instances · sha256 {got[:16]}… matches")
PY

  asset="$OUT/scope-$TAG-$ds.tar.gz"
  echo "[pack] $asset"
  tar -czf "$asset" -C "$REPO" "${pack[@]/#/$src/}"
  ls -lh "$asset" | awk '{print "        ", $5}'
done

( cd "$OUT" && sha256sum ./*.tar.gz > SHA256SUMS )

{
  cat <<'HEAD'
# SCOPE v1.0.0

Fixed experimental artifacts for reproducing the reported results. With the repository code and
these assets, training and evaluation can be reproduced without downloading the raw corpus.

## Assets

HEAD
  for ds in "${DS_LIST[@]}"; do
    echo "- \`scope-$TAG-$ds.tar.gz\` — $ds"
  done
  cat <<'BODY'
- `SHA256SUMS` — checksums

Each archive unpacks into `data/preprocessed/{dataset}/`.

| File | Produced by |
|---|---|
| `queries.parquet` | [3] review → natural-language query (LLM) |
| `cards.jsonl` | [4] item semantic cards (LLM) |
| `split_manifest.json` | [2] train/valid/test split (immutable) |
| `leak_dropped_uids.json` | definition of the canonical evaluation population |
| `processed/` | [5] the instances used for the reported training and evaluation |

## Usage

```bash
git clone <repo> && cd SCOPE
pip install -r requirements.txt
SCOPE_REPO=<owner>/<repo> bash scripts/fetch_release_assets.sh
bash run.sh --dataset books --stages 5,6,train,test
```

`--stages 6,train,test` starts from the shipped `processed/` and skips stage [5].

## Not included

- **The Amazon Reviews 2023 corpus** — public data, not redistributed here.
  Fetch it with `python src/download_data.py --category Books`.
- **`embeddings/`** — regenerated by `--stages 6` with the frozen encoder.
- **Data artifacts for Beauty & Personal Care and Video Games** — the same implementation supports
  both domains, which can be rebuilt locally from the public corpus with stages [1]–[5].
BODY
} > "$OUT/RELEASE_NOTES.md"

echo
echo "done: $OUT/"
ls -1 "$OUT"
echo
echo "upload:"
echo "  gh release create $TAG $OUT/*.tar.gz $OUT/SHA256SUMS \\"
echo "      --title \"SCOPE $TAG\" --notes-file $OUT/RELEASE_NOTES.md"
